### ISSUE TITLE
Unable to add custom repo for B-Hyve Add-on

### ISSUE THREAD

**Issue by MelCrypto** [sebr/bhyve-home-assistant#1]
Hello,

As recommended by the install guide I am trying to add the custom repo : https://github.com/sebr/bhyve-home-assistant to my HA config and it never loads. The error : 
20-01-05 01:28:26 INFO (MainThread) [hassio.store.git] Clone add-on https://github.com/sebr/bhyve-home-assistant repository
20-01-05 01:28:29 ERROR (MainThread) [hassio.utils.json] Can't read json from /data/addons/git/6e2ba233/repository.json: [Errno 2] No such file or directory: '/data/addons/git/6e2ba233/repository.json'
20-01-05 01:28:29 WARNING (MainThread) [hassio.store.data] Can't read repository information from /data/addons/git/6e2ba233/repository.json

Is seen in my event logs,

Any idea what I could do different ?

**Comment by sebr** [comment]
Hi @MelCrypto - haven't seen this before. How did you add the repo?

My config uses `sebr/bhyve-home-assistant` with `integration` category

**Comment by sebr** [comment]
The integration is now included as part of HACS default, so this issue is no longer relevant.

Thanks!
