### ISSUE TITLE
Services not appearing

### ISSUE THREAD

**Issue by whitestripes32** [sebr/bhyve-home-assistant#104]
**Describe the bug**
I installed the integration via HACS and from documentation, the services that i can call via automation should also appear.

When I call a watering event i get errors like this in my log

Logger: homeassistant.components.automation.back_yard_watering
Source: components/automation/__init__.py:514
Integration: Automation ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 17:24:34 (2 occurrences)
Last logged: 17:24:42

Error while executing automation automation.back_yard_watering: Unable to find service bhyve.start_watering

**Comment by sebr** [comment]
Sorry about that, fixed in 2.2.1

**Comment by whitestripes32** [comment]
Tested and working! Thanks so much for the quick fix
