### ISSUE TITLE
Rain delay cause doesnt fill in after initial fill in (BUG) but not a huge deal.

### ISSUE THREAD

**Issue by monsieurlatte** [sebr/bhyve-home-assistant#11]
I have noticed that in HA (all builds that I have used with b-hyve) the first rain delay reason, IE it will say rain or freeze or whatever, but then after that it will have no data in there (until I restart HA again).

**Comment by sebr** [comment]
@monsieurlatte thanks for the report, I've released a fix in version `0.1.12`
