### ISSUE TITLE
Deprecation warnings from component on 0.110.0

### ISSUE THREAD

**Issue by mdegat01** [sebr/bhyve-home-assistant#12]
I ran check config before upgrading to 0.110 and received these warnings from its output:
```
WARNING:homeassistant.components.switch:SwitchDevice is deprecated, modify BHyveZoneSwitch to extend SwitchEntity
WARNING:homeassistant.components.binary_sensor:BinarySensorDevice is deprecated, modify BHyveRainDelayBinarySensor to extend BinarySensorEntity
```
Since these are only warnings I assume the integration still works for now (haven't actually upgraded yet, working out other issues first).  But wanted to get an issue down to let you know.

Ludeeus has been linking to [this blog post](https://developers.home-assistant.io/blog/2020/05/14/entity-class-names/) to explain what's going on when people comment that they see this warning in their logs on 0.110.  Seems like just a name change for some base classes.

[EDIT] Removed one log as I realized the 3rd one was coming from a different component.  Going to make an issue there next.

**Comment by sebr** [comment]
Fixed - thanks for the report!
