### ISSUE TITLE
Support with B-hyve XD

### ISSUE THREAD

**Issue by gdreelin** [sebr/bhyve-home-assistant#123]
**Describe the new device**
This is the newer version of the smart hose time #24511P  and uses the newer hub #21008. I would love to get this newer version to work in Home Assistant.

**Comment by sebr** [comment]
Can you please describe what the current behaviour is when using this device with the integration?

**Comment by sebr** [comment]
According to [this comment](https://github.com/sebr/bhyve-home-assistant/discussions/56#discussioncomment-2385300) the BHyve XD device works.

If you are having trouble with it please provide detailed information on what behaviours you are seeing.

**Comment by gdreelin** [comment]
Well ok I must have done something wrong. I will give it another try.  Thanks for researching it.
