### ISSUE TITLE
Obtain error: "entity_category must be a valid EntityCategory instance"

### ISSUE THREAD

**Issue by jgarbayo** [sebr/bhyve-home-assistant#125]
**Describe the bug**
 When starting Home assistant the following error  is received in the bhyve input. It only appears for the switch entity and the sensor entity, it does not appear for bynary-sensor

Logger: homeassistant.components.switch
Source: helpers/entity_registry.py:382
Integration: Interruptor (documentation, issues)
First occurred: 14:58:10 (2 occurrences)
Last logged: 14:58:10

Error adding entities for domain switch with platform bhyve
Error while setting up bhyve platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 382, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

Logger: homeassistant.components.sensor
Source: helpers/entity_registry.py:382
Integration: Sensor (documentation, issues)
First occurred: 14:58:10 (2 occurrences)
Last logged: 14:58:10

Error adding entities for domain sensor with platform bhyve
Error while setting up bhyve platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 514, in _async_add_entity
    entry = entity_registry.async_get_or_create(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_registry.py", line 382, in async_get_or_create
    raise ValueError("entity_category must be a valid EntityCategory instance")
ValueError: entity_category must be a valid EntityCategory instance

**BHyve devices**
 Orbit 94550 Programador de riego WiFi 12 Estaciones con Tapa B-Hyve - Control Desde el teléfono Mediante App - 12 Zonas de riego.  https://www.amazon.es/gp/product/B07254NJC3/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1  

**Logs**

```log
DEBUG (MainThread) [custom_components.bhyve] Devices:
DEBUG (MainThread) [custom_components.bhyve] Programs:
```

**Comment by txwindsurfer** [comment]
I am also getting this same error after installing HS 22.5.3

**Comment by sebr** [comment]
Are you using version `2.2.2` of the integration?

**Comment by jgarbayo** [comment]
First of all , thanks for the integration Sebr, i´m from spain, and my english is not so good, sorry.
I´m runing de version 2.2.1, in fact i reloaded the intergration thru "HACS" the integration and apears de 2.2.1 versión again. In my case the core version is  HS 22.5.2.

How can i upgrade to 2.2.1? i´m not an expert in programing!

**Comment by sebr** [comment]
Thanks, that is odd indeed! I published [version `2.2.2`](https://github.com/sebr/bhyve-home-assistant/releases/tag/2.2.2) a month ago...

**Comment by txwindsurfer** [comment]
I am also very, very thankful for your work on this integration.  I am seeing the same thing as @jgarbayo when I look for a new version or attempt to redownload. The lastest version appears to be 2.2.1.  I did redownload the "main" version which shows up at the bottom of the list.  This version does not produce any errors and inspecting the integration shows a version number of 5158382.  Could this be 2.2.2?

**Comment by jgarbayo** [comment]
> I am also very, very thankful for your work on this integration. I am seeing the same thing as @jgarbayo when I look for a new version or attempt to redownload. The lastest version appears to be 2.2.1. I did redownload the "main" version which shows up at the bottom of the list. This version does not produce any errors and inspecting the integration shows a version number of [5158382](https://github.com/sebr/bhyve-home-assistant/commit/5158382b19c8e31b3abb5339ed382cb4cad7cbb2). Could this be 2.2.2?

At the bottom of what list, please?

**Comment by txwindsurfer** [comment]
@jgarbayo go to HACS, Integrations, Orbit then the 3 dots. Select redownload and the arrow in the Select Version list.  Main is at the bottom of this list

**Comment by jgarbayo** [comment]
Yes, thankyou very much, now works with no errors. Grat itegration!  MAny thanks!
