### ISSUE TITLE
Upgraded to v2.2.3 and now get error 500 on startup from bhyve

### ISSUE THREAD

**Issue by kkellner** [sebr/bhyve-home-assistant#128]
**Describe the bug**
Upgraded to v2.2.3 (also upgraded to 2022.5.3 from 2022.4.x of HA at the same time).  Now at startup of HA I don't have any bhyve devices/entities.  When I look at the log files, I see: Unexpected error 500, message='Invalid response status', url=URL('wss://api.orbitbhyve.com/v1/events')

**BHyve devices**
Normally I would have about 7 zones (a 6 zone timer and 1 hose timer) show up in HA.

**Logs**

This error originated from a custom integration.

Logger: custom_components.bhyve.pybhyve.websocket
Source: custom_components/bhyve/pybhyve/websocket.py:142
Integration: Orbit BHyve Integration (documentation)
First occurred: 6:54:46 PM (1 occurrences)
Last logged: 6:54:46 PM

Unexpected error 500, message='Invalid response status', url=URL('wss://api.orbitbhyve.com/v1/events')

**Comment by kkellner** [comment]
FYI, I downgraded to v2.2.2 and its working again.

**Comment by realcanadrian** [comment]
I'm seeing the same on 2.2.3, and downgrading to 2.2.2 also fixes it for me.

**Comment by dahem0n** [comment]
Looks like 2.2.3 fixes an issue in Home Assistant Core 2022.5.5, but causes an issue on Home Assistant Core 2022.5.4 where 2.2.2 works fine

**Comment by sebr** [comment]
Anybody seeing this anymore?

**Comment by kkellner** [comment]
2022.6.7 of HA and 2.2.3 of bhyve works fine.
