### ISSUE TITLE
Beta setup instructions?

### ISSUE THREAD

**Issue by dcmeglio** [sebr/bhyve-home-assistant#136]
I installed 3.0.0-b1 via HACS, now what? It says to configure using the UI. I click Add Integration. I can't find anything that appears related to this integration. What am I missing?

**Comment by sebr** [comment]
Others have reported that you might need to do a hard refresh of your browser for the b-hyve integration to show up

**Comment by dcmeglio** [comment]
Yup that’s what it was. Haven’t had to do this with other integrations though.
