### ISSUE TITLE
Integration does not support platform setup in Home assistant

### ISSUE THREAD

**Issue by stamandr** [sebr/bhyve-home-assistant#137]
Getting the following errors in Home Assistant after updating to Beta 2

The bhyve platform for the switch integration does not support platform setup. Please remove it from your config
The bhyve platform for the binary_sensor integration does not support platform setup. Please remove it from your config.
The bhyve platform for the sensor integration does not support platform setup. Please remove it from your config.

**Comment by sebr** [comment]
Thanks for the report, this duplicates #134
