### ISSUE TITLE
Feature Request: Service to run program

### ISSUE THREAD

**Issue by disforw** [sebr/bhyve-home-assistant#145]
Have you looked in to a service that will execute a defined program?
If not I'll create a PR for it.

**Comment by sebr** [comment]
I have not looked into this (I assume it's possible but not ever seen a way to do it). Would be great if you could investigate :)

**Comment by disforw** [comment]
Here are my findings when monitoring the WS. Should I just create a service that starts watering a program? Because we already have a switch to enable/disable a program, dont want to make it confusing.

**Start Water by Zone**
{"event":"change_mode","mode":"manual","program":null,"stations":[{"station":3,"run_time":10.0}],"device_id":"xXxxXxxxXXxXXxxXxxXXxxXXx","timestamp":"2022-07-21T05:15:02.000Z"}
{"event":"watering_in_progress_notification","program":"manual","current_station":3,"run_time":10.0,"started_watering_station_at":"2022-07-21T05:15:02.000Z","rain_sensor_hold":false,"device_id":"xXxxXxxxXXxXXxxXxxXXxxXXx","timestamp":"2022-07-21T05:15:02.000Z"}

**Start Water Program**
{"event":"change_mode","mode":"manual","program":"a","stations":[],"device_id":"xXxxXxxxXXxXXxxXxxXXxxXXx","timestamp":"2022-07-21T05:15:40.000Z"}
{"event":"watering_in_progress_notification","program":"a","current_station":1,"run_time":21.0,"started_watering_station_at":"2022-07-21T05:15:40.000Z","rain_sensor_hold":false,"device_id":"xXxxXxxxXXxXXxxXxxXXxxXXx","timestamp":"2022-07-21T05:15:40.000Z"}

**Comment by skarragallagher** [comment]
i would love to see this implemented

**Comment by disforw** [comment]
Created PR #164 to implement
