### ISSUE TITLE
Found this in checkin HA LOGS

### ISSUE THREAD

**Issue by meremortals70** [sebr/bhyve-home-assistant#154]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:193 
Integration: Sensor (documentation, issues) 
First occurred: 5:45:48 PM (1 occurrences) 
Last logged: 5:45:48 PM

The bhyve platform for the sensor integration does not support platform setup. Please remove it from your config.

I have two hubs in my system, one Gen1 and one Gen2.

![image](https://user-images.githubusercontent.com/52735978/187064363-4cc8cb99-5362-416f-add4-edfad3e49d91.jpeg)

Let me know if you need further information please?

**Comment by sebr** [comment]
Did you recently upgrade from 2.x to 3.x?

**Comment by meremortals70** [comment]
Found the problem, still had an entry in my sensor.yaml after a whole lot of commented out entries
