### ISSUE TITLE
bhyve_next_watering.py  -  Error executing script: 'device_name'

### ISSUE THREAD

**Issue by psicard** [sebr/bhyve-home-assistant#16]
When I try to run the bhyve_next_watering.py script, I get the error "Error executing script: 'device_name'"
I am calling the service "python_script.bhyve_next_watering" with "entity_id: switch.back_trees_zone".  I only have one zone at the moment.

Not sure if this will help...
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/python_script/__init__.py", line 205, in execute
    exec(compiled.code, restricted_globals)
  File "bhyve_next_watering.py", line 7, in <module>
  File "/usr/local/lib/python3.7/site-packages/RestrictedPython/Eval.py", line 35, in default_guarded_getitem
    return ob[index]
KeyError: 'device_name'

**Comment by sebr** [comment]
The script currently only works when using the latest alpha of this integration, apologies for not making that clearer. I’ll clear that up in the readme

**Comment by sebr** [comment]
I've fixed the confusion by keeping version `0.1.x` on the `main` branch, and the `0.2.x` version on branch `develop`. This means the readme shows the current stable documentation.
