### ISSUE TITLE
If HA reboots during auto program run it turns off sprinklers

### ISSUE THREAD

**Issue by qwserty** [sebr/bhyve-home-assistant#17]
If during the automation program and the sprinklers are running and HA gets rebooted it causes the currently running program to stop and turns off the sprinklers.

I've noticed that if an automation trigger in HA goes off it switches the system to manual while HA is in control and stops any running program. I've changed my automation system to not run during the bhyve program run times to avoid this. I'm wondering if maybe during the initial startup of the bhyve component it is switching the system to manual for a couple seconds causing the auto system to shutdown.

**Comment by sebr** [comment]
@qwserty the integration itself doesn't set any state for the entities on boot, but it's quite possible that when HA restarts it tries to set the last known state.

Can you please share your automations so I can take a look?

**Comment by qwserty** [comment]
I do not have an automation for the sprinkler system in HA at least not one
that runs the actual sprinkler system. I do have a program on the bhyve
unit that runs the sprinklers and sensor.backyard_sprinklers_zone_state is
always in auto., but I do have some motion detection that sets off some
sprinklers to keep animals out of our flower beds. When those go off the
state switches to manual, but it isn't setup to run during the bhyve
program. This is what I have

On the Bhyve unit:
program a

enabled: true
name: FrontBackandSouthYD
is_smart_program: false
start_times:
  - '04:00'
frequency:
  type: days
  days:
    - 1
    - 4
run_times:
  - run_time: 23
    station: 3


automation.yaml for motion detection on cameras. It doesn't run during the
sprinkler auto time on bhyve
 - id: '1591203662009'
  alias: 'Motion Detection: Security Sprinklers on'
  description: Turn on Security Sprinklers when dogs are in an area
  trigger:
  - entity_id: binary_sensor.motion_backyard
    platform: state
    to: 'on'
  condition:
  - after: 09:00:00
    before: '22:00:00'
    condition: time
  action:
  - entity_id: switch.sprinkler_security_zone
    service: switch.turn_on
  - data:
      brightness_pct: 100
      effect: custom
      entity_id: light.dragon_lamp
    entity_id: light.dragon_lamp
    service: light.turn_on
- id: '1591203910804'
  alias: 'Motion Detection: Security Sprinklers off after 30 seconds'
  description: Turn security Sprinklers off after 60 seconds
  trigger:
  - entity_id: binary_sensor.motion_backyard
    for: 0:00:30
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: sensor.sprinkler_security_zone_state
      state: manual
  action:
  - entity_id: switch.sprinkler_security_zone
    service: switch.turn_off
  - data: {}
    entity_id: light.dragon_lamp
    service: light.turn_off

I can test more and see if I can find a reason for it.
Thank you.

**Comment by sebr** [comment]
@qwserty I can't see any obvious reason as to what would be causing this. Can you help me understand how you use the `sprinkler_security_zone_state` entity? Where/how do you change the value from `auto` to `manual` ?

The only thing which I can guess might be happening is unexpected triggers for the automations - the automations will be invoked if only entity attributes change (even if the state value hasn't changed). You could try:

```yaml
  trigger:
  - entity_id: binary_sensor.motion_backyard
    for: 0:00:30
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: template
      value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"
    - condition: state
      entity_id: sensor.sprinkler_security_zone_state
      state: manual
```

**Comment by sebr** [comment]
@qwserty did you make any progress on this?

**Comment by qwserty** [comment]
Not really, but I haven't had time to mess around with it lately.. I've
completely disabled the auto system on the sprinkler controller now and
have home assistant running it all and that seems to have fixed the
problem. Now if the sprinklers are on and the computer resets for some
reason the controller holds the current running zone and time home
assistant sent and doesn't shutdown.

Thank

**Comment by sebr** [comment]
Very well, I'll close this issue then :).

Please let me know if you take another look and can provide more info - happy to help where I can!

**Comment by qwserty** [comment]
Sure thing.. Thank you.
