### ISSUE TITLE
Issue adding second B-hyve device

### ISSUE THREAD

**Issue by Camwise1** [sebr/bhyve-home-assistant#171]
I’m trying to add a new hose timer to an existing integration.
The new device shows on the list and is unchecked but checking it and hitting submit generates this message: 
User input malformed: 57c20be4e4b0c6d7dc5671ba is not a valid option for dictionary value @ data['devices']
![940D5DD4-B0B8-4536-8571-F0173A4D6472](https://user-images.githubusercontent.com/74271006/220155658-c0ca7916-a6ac-49ab-8d45-35caf9dfd7cb.png)

Any suggestions?

**Comment by sebr** [comment]
Can you please upload device diagnostics? Instructions were in the bug report template:

```
**Describe the bug**
<!-- A clear and concise description of what the bug is. -->

**Expected behaviour**
<!-- A clear and concise description of what you expected to happen. -->

**BHyve devices**
<!-- Please detail the number and types of devices in your BHyve configuration. -->

**Device Diagnostics**
<!--

Please attach the Home Assistant diagnostics for the B-hyve device. Sensitive information is redacted when compiling the diagnostic data.

* Home Assistant diagnostics: https://www.home-assistant.io/integrations/diagnostics/
* Diagnostic data implementation: https://github.com/sebr/bhyve-home-assistant/blob/main/custom_components/bhyve/diagnostics.py
* Example of how to generate: https://user-images.githubusercontent.com/81972/179869298-3d2a33ca-f847-4a25-8e77-20757e49f914.png

-->
```

**Comment by sebr** [comment]
Closing due to lack of information
