### ISSUE TITLE
Will not be compatible with 2023.3

### ISSUE THREAD

**Issue by dcmeglio** [sebr/bhyve-home-assistant#172]
**Describe the bug**

The following message appears in the logs:
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for bhyve using this method at custom_components/bhyve/__init__.py, line 124: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

**Expected behaviour**

Update code to use async_forward_entry_setups (very easy change)

**BHyve devices**

**Device Diagnostics**

**Comment by sebr** [comment]
This was fixed and released in [3.1.2](https://github.com/sebr/bhyve-home-assistant/releases/tag/3.1.2)

**Comment by dcmeglio** [comment]
Hmm odd, HACS was saying 3.1.1 was latest until I forced it to update the repo information. Can confirm this fixes it.
