### ISSUE TITLE
Rain delay for a specified amount of time

### ISSUE THREAD

**Issue by Evigami** [sebr/bhyve-home-assistant#174]
**Is your feature request related to a problem? Please describe.**
In the B-Hyve app, there is an option for how long you want a rain delay to last. Could you add an option in the integration to specify how long you want the rain delay to last? There are different amounts of precipitation to account for and one day doesn't work for every rainstorm.
**Describe the solution you'd like**
A dimmer light or multiple lightbulbs for 12h, 24h, 2d, 3d, 4d.

**Describe alternatives you've considered**

**Additional context**

**Comment by sebr** [comment]
The `bhyve.enable_rain_delay` service will allow you to set a rain delay with a specified number of hours, please see https://github.com/sebr/bhyve-home-assistant#services
