### ISSUE TITLE
Error setting up entry [username] for bhyve

### ISSUE THREAD

**Issue by tekwreck** [sebr/bhyve-home-assistant#176]
**Describe the bug**
Initial setup with integration using the Wifi Hub with the Water Hose Timer (4 port). Username / Password work fine then ask me to select the device which shows the Water Timer. The config UI closes and just shows error on the Integrations page for this integrations

Logger: homeassistant.config_entries
Source: custom_components/bhyve/__init__.py:124
Integration: Orbit B-hyve ([documentation](https://github.com/sebr/bhyve-home-assistant/blob/master/README.md))
First occurred: 2:51:40 PM (1 occurrences)
Last logged: 2:51:40 PM

Error setting up entry [myusername] for bhyve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bhyve/__init__.py", line 124, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

**Expected behaviour**
I assume no error

**BHyve devices**
WIfi Hub
4 port hose timer

**Device Diagnostics**

**Comment by sebr** [comment]
Which version of HA are you running? The integration has a minimum supported version of 2022.8.

**Comment by tekwreck** [comment]
Thanks I upgraded HA and it resolved itself.
