### ISSUE TITLE
Battery Level Unknown

### ISSUE THREAD

**Issue by rob51i03** [sebr/bhyve-home-assistant#18]
Home Assistant 0.111.4
HACS 1.1.0
byhve-home-assistant 0.1.13
B-hyve Wireless Hub Firmware 0022
B-hyve Smart Hose Timer Firmware 0041

Entities created in HA and returning values:
- switch.back_yard_zone : off
- sensor.back_yard_zone_state : auto
- binary_sensor.rain_delay_smart_hose_timer_1 : off
- sensor.battery_level_smart_hose_timer_1 : unknown

Battery level sensor always shows Unknown (currently 100% in Byhve Android App).

**Comment by sebr** [comment]
@rob51i03 can you please check that there isn’t a duplicate entity that was created, and if not then please enable debug logging and provide me your devices output from the HA log

**Comment by rob51i03** [comment]
Hi @sebr, this might actually be a B-hyve problem rather than an integration problem. I checked the smart hose timer status on https://techsupport.orbitbhyve.com and the battery level isn't showing there either. I've raised it with Orbit tech support, hopefully they can resolve that issue and then I'll re-check HA.

**Comment by rob51i03** [comment]
Confirmed, this was a B-hyve problem. Now the issue with B-hyve is resolved, the battery sensor info is coming through to HA correctly.
