### ISSUE TITLE
Install help please

### ISSUE THREAD

**Issue by MnM001** [sebr/bhyve-home-assistant#19]
HI,

I have installed HACS and added this repo in there.
Now I am stuck. 
Where do the below go to? What files and location? (sorry kind of new to this).

bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password

sensor:
  - platform: bhyve

binary_sensor:
  - platform: bhyve

switch:
  - platform: bhyve

**Comment by sebr** [comment]
This information goes in your `configuration.yaml` file

https://www.home-assistant.io/docs/configuration/
