### ISSUE TITLE
Integration local or cloud and sensor rain

### ISSUE THREAD

**Issue by pepsonEL** [sebr/bhyve-home-assistant#193]
Hi. I think abou buy this controller and integrate it with Home Assistant. But tell me this integration works by cloud or by local LAN network ? 

Also if i use whit this controller rain sensor connected to controller it also will be show as binary sensors in home assistant ?

**Comment by WayneManion** [comment]
The integration works by cloud. There is a rain delay binary sensor, but I'm not sure what it does. I use Home Assistant to automate my irrigation programs based on forecast data. I don't have any programs set on B-Hyve itself. 

I use the HT34 four-port hose timers and they don't have Wi-Fi themselves. They communicate with an Orbit WI-Fi (gen 2) hub using Bluetooth. I am pretty sure the hub is just an ESP32.

**Comment by sebr** [comment]
Thanks for responding @WayneManion :)

@pepsonEL any further questions please use discussions :)

**Comment by pepsonEL** [comment]
Ok thanks
