### ISSUE TITLE
HT25 Smart Hose Timer switch and sensors greyed out

### ISSUE THREAD

**Issue by mash2k3** [sebr/bhyve-home-assistant#196]
**Describe the bug**
I can not control the HT25 Smart Hose Timer connected via Gen 1 wifi hub. All but schedule is greyed out but you can not turn off schedule via integration either. I don't get any status changes either.

![image](https://github.com/sebr/bhyve-home-assistant/assets/1356023/fd596409-d5be-4acc-9b62-b75f22cecad4)

**Expected behaviour**
Be able to control device and get sensor data.

**BHyve devices**
Wifi Hub gen 1 BH1-0001
Smart Hose Tap Timer HT25-0000
[config_entry-bhyve-ada2faf8b7c0beffb024b5c6bc6c7b82.json.txt](https://github.com/sebr/bhyve-home-assistant/files/11583233/config_entry-bhyve-ada2faf8b7c0beffb024b5c6bc6c7b82.json.txt)

**Device Diagnostics**
attached

**Comment by sebr** [comment]
Please upgrade to 3.1.3 which was recently released and let me know if you still have this issue?

Thanks

**Comment by mash2k3** [comment]
Still greyed out but this time i can control schedule on and off and i have the battery sensor.

![image](https://github.com/sebr/bhyve-home-assistant/assets/1356023/a1ca21ff-1810-4537-8187-c9d359b5a1b9)

**Comment by mash2k3** [comment]
Okay i got it working, i had to go to this site techsupport.orbitbhyve.com and sync the hose timer. Then in HA i reloaded the orbit integration.

![image](https://github.com/sebr/bhyve-home-assistant/assets/1356023/b18f70f5-c411-40bd-9f23-3e5d1ea34347)

**Comment by sebr** [comment]
Thanks for closing the loop.
