### ISSUE TITLE
Battery showing 0

### ISSUE THREAD

**Issue by kramttocs** [sebr/bhyve-home-assistant#202]
Battery values for all devices (3 XD valves) are showing 0. BHyve app does show the value for each.

**Comment by sebr** [comment]
Please upload your diagnostics file as requested in the issue template.

I will close this until the information is provided.

**Comment by kramttocs** [comment]
Sorry about that. Here you go
[config_entry-bhyve-cd8c33daba9f795fdffe277e1e3520d9.json.txt](https://github.com/sebr/bhyve-home-assistant/files/11655891/config_entry-bhyve-cd8c33daba9f795fdffe277e1e3520d9.json.txt)

**Comment by kramttocs** [comment]
Hey @sebr - is that enough to reopen this?
