### ISSUE TITLE
Platform Support not supported after HASS update

### ISSUE THREAD

**Issue by MadOtis** [sebr/bhyve-home-assistant#205]
**Describe the bug**
Since updating HASS to the latest (2023.6.0 & 2023.6.1) the bhyve integration reports an error.  The following text is visible in the system settings page:
Platform support not supported
The bhyve platform for the sensor integration does not support platform setup.

Please remove it from your configuration and restart Home Assistant to fix this issue.

**Expected behaviour**
Should see no errors

**BHyve devices**
2 Orbiy Bhyve hose timers

**Device Diagnostics**
None

Duplicated by simply updating HASS to 2023.6.0 or later.

**Comment by sebr** [comment]
> Please remove it from your configuration and restart Home Assistant to fix this issue.

You need to follow the instructions which the log provide you 😄 

i.e. remove `bhyve` from `configuration.yaml`. The integration is configured from the UI and this has been the case [since version 3](https://github.com/sebr/bhyve-home-assistant/releases/tag/3.0.0).
