### ISSUE TITLE
No platform support 

### ISSUE THREAD

**Issue by timknowlden** [sebr/bhyve-home-assistant#210]
**Describe the bug**
![image](https://github.com/sebr/bhyve-home-assistant/assets/73787006/956627c9-d3b8-43db-b31a-7a3e9a1eeee9)

**BHyve devices*
Orbit bhyve 4 way zone controller

**Device Diagnostics**
<!--

Please attach the Home Assistant diagnostics for the B-hyve device. Sensitive information is redacted when compiling the diagnostic data.

Since latest Home assistant update, it seems the integration doesn't support something?

**Comment by sebr** [comment]
Remove the `bhyve` entries from `configuration.yaml`
