### ISSUE TITLE
Failed to set up.  Check the logs

### ISSUE THREAD

**Issue by TGSnedecor** [sebr/bhyve-home-assistant#213]
I just added a new B-hyve smart sprinkler valve.  I have an account successfully set up with Orbit.  I thought I followed the instructions.  I installed the software from HACS, and restarted homeassistant.  I selected the integration and installed it.  I entered my credentials.  It found my hose timer.  I went to the integration and got the error message above.  I checked the logs and found the following: 

Log Details (ERROR)
This error originated from a custom integration.
Logger: homeassistant.config_entries
Source: custom_components/bhyve/__init__.py:124
Integration: Orbit B-hyve ([documentation](https://github.com/sebr/bhyve-home-assistant/blob/main/README.md))
First occurred: 4:45:13 PM (1 occurrences)
Last logged: 4:45:13 PM

Error setting up entry thesxxxxx@hotmail.com for bhyve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/bhyve/__init__.py", line 124, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

**Comment by sebr** [comment]
Which version of HA?

**Comment by TGSnedecor** [comment]
2022.4.7  (8.5)

**Comment by sebr** [comment]
Right - the integration needs 2023.3 or later. I'll update the manifest to fail on earlier versions.
