### ISSUE TITLE
Switches fail to initialize

### ISSUE THREAD

**Issue by MizterB** [sebr/bhyve-home-assistant#217]
**Describe the bug**
When loading the BHyve integration, an error is thrown is switches are no longer created for controlling the faucet.  Diagnostic sensors load fine.

The error seems to occur because the code is expecting a watering schedule ("next start_time") to be defined for the device.  I do not have a schedule defined - I water manually (typically through this integration!).

**Expected behaviour**
A switch should be created that allows me to control the flow of the faucet.

**BHyve devices**
```
HT25-0000
by Orbit BHyve
Firmware: 0032
Hardware: HT25-0000
```

**Device Diagnostics**
```
2023-08-22 15:13:01.859 ERROR (MainThread) [homeassistant.components.switch] Error while setting up bhyve platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 362, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bhyve/switch.py", line 183, in async_setup_entry
    BHyveZoneSwitch(
  File "/config/custom_components/bhyve/switch.py", line 388, in __init__
    super().__init__(hass, bhyve, device, name, icon, SwitchDeviceClass.SWITCH)
  File "/config/custom_components/bhyve/__init__.py", line 268, in __init__
    self._setup(device)
  File "/config/custom_components/bhyve/switch.py", line 420, in _setup
    ).isoformat()
      ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isoformat'
```

**Comment by sebr** [comment]
@MizterB Please upload your device diagnostics

**Comment by MizterB** [comment]
Here you go.
[config_entry-bhyve-a5799276bb76e228c5e4f066a9bb14ef.json.txt](https://github.com/sebr/bhyve-home-assistant/files/12448120/config_entry-bhyve-a5799276bb76e228c5e4f066a9bb14ef.json.txt)

**Comment by fyyzer** [comment]
Just wanted to confirm I'm seeing this same behavior with the HT25-0000 as well as with my HT31-0001 devices using 3.2.1 b1

**Comment by pjv** [comment]
Same on my HT32-0001

My lettuce died.

@sebr can you review and merge [this PR](https://github.com/sebr/bhyve-home-assistant/pull/219) which should fix this issue?

**Comment by sebr** [comment]
Apologies about the extended delay on this - I've merged the PR and will do a release asap.

**Comment by AndrewEAUS** [comment]
next_start_time_raw = status.get("next_start_time")
            if next_start_time_raw is not None:
                next_start_time = orbit_time_to_local_time(
                    next_start_time_raw
                ).isoformat()
                next_start_programs = status.get("next_start_programs")
                self._attrs.update(
                    {
                        ATTR_NEXT_START_TIME: next_start_time,
                        ATTR_NEXT_START_PROGRAMS: next_start_programs,
                    }
                )
