### ISSUE TITLE
Add-on stopped functioning, not sure how to address.

### ISSUE THREAD

**Issue by ShooterQ** [sebr/bhyve-home-assistant#221]
**Describe the bug**
Noticed today that my sprinkler entities fell off. Orbit integration reads as "Failed Setup, will Retry"
![image](https://github.com/sebr/bhyve-home-assistant/assets/37904834/7194c4dd-184c-4f97-85fb-f002002881e3)

**Expected behaviour**
Reloading the integration doesn't seem to help. Trying to check the configuration to make sure all is well produces a separate error. 

![image](https://github.com/sebr/bhyve-home-assistant/assets/37904834/ee7c2aa5-8d0d-4f57-bc5b-ac1dfc60f1a8)

**BHyve devices**

Using one B-Hyve multizone controller and 3 hose units.

![image](https://github.com/sebr/bhyve-home-assistant/assets/37904834/8a4d042c-f9e4-4d4a-abb1-193737f89257)

**Device Diagnostics**
<!--

Please attach the Home Assistant diagnostics for the B-hyve device. Sensitive information is redacted when compiling the diagnostic data.

* Home Assistant diagnostics: https://www.home-assistant.io/integrations/diagnostics/
* Diagnostic data implementation: https://github.com/sebr/bhyve-home-assistant/blob/main/custom_components/bhyve/diagnostics.py
* Example of how to generate: https://user-images.githubusercontent.com/81972/179869298-3d2a33ca-f847-4a25-8e77-20757e49f914.png

I don't see the menu button for generating the diagnostic data; perhaps outdated or part of my problem?

![image](https://github.com/sebr/bhyve-home-assistant/assets/37904834/4961d840-b3ab-446d-bf3d-cbb7025f78f8)

**Comment by sebr** [comment]
Can you please look at the Home Assistant logs and provide further information? I can't help without this :)

**Comment by ShooterQ** [comment]
Hello, sorry about that. This it the only log I'm seeing pertaining to Orbit B-Hyve, shows up with the automatic retry as well as my manual retry.

`2023-09-30 12:42:19.985 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Orbit B-Hyve Sprinkler' for bhyve integration not ready yet; Retrying in background`

![image](https://github.com/sebr/bhyve-home-assistant/assets/37904834/94421a8f-9ea0-4a5f-a648-a96cec3598b1)

Version from the full log is not any different: 

![image](https://github.com/sebr/bhyve-home-assistant/assets/37904834/f372caac-20c9-4515-b2de-fb9e59851fab)

Should I be looking for something more verbose?

**Comment by ShooterQ** [comment]
I'm not sure what happened, but everything is working fine now with no input on my part. No idea.
