### ISSUE TITLE
Missing Sensors after Modification to battery sensor

### ISSUE THREAD

**Issue by Shredder5262** [sebr/bhyve-home-assistant#222]
![2023-10-06 18_08_36-Settings – Home Assistant - Vivaldi](https://github.com/sebr/bhyve-home-assistant/assets/59770346/053ece46-ad50-4f39-a42d-74a3031e7611)
**Describe the bug**
I seem to have only missing and/or non-responsive sensors after installing a beta update to check if a previous battery sensor was updated which is also still inaccurate according to my app. I am not able to see any of the zone sensors and toggles associated with the app.  Also I see various errors in the HA logs. 

**Expected behaviour**

**BHyve devices**
[]
(https://www.amazon.com/Orbit-24639-B-hyve-4-Port-Watering/dp/B09KJZKVNS/ref=sr_1_5_pp?crid=1ZZBBRBAWBS8U&keywords=orbit+b+hyve&qid=1696634078&sprefix=orbit+b+hyve%2Caps%2C93&sr=8-5)

**Device Diagnostics**

Various errors, i will attatch a diag log later

raceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bhyve/switch.py", line 183, in async_setup_entry
    BHyveZoneSwitch(
  File "/config/custom_components/bhyve/switch.py", line 388, in __init__
    super().__init__(hass, bhyve, device, name, icon, SwitchDeviceClass.SWITCH)
  File "/config/custom_components/bhyve/__init__.py", line 268, in __init__
    self._setup(device)
  File "/config/custom_components/bhyve/switch.py", line 420, in _setup
    ).isoformat()
      ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isoformat'

**Comment by sebr** [comment]
Closed in https://github.com/sebr/bhyve-home-assistant/pull/219 and released in [3.2.1](https://github.com/sebr/bhyve-home-assistant/releases/tag/3.2.1)
