### ISSUE TITLE
RuntimeWarning: coroutine 'BHyveWebsocketEntity.async_update' was never awaited super().async_update()

### ISSUE THREAD

**Issue by KJThaDon** [sebr/bhyve-home-assistant#223]
Getting logs full of these errors

`/config/custom_components/bhyve/sensor.py:155: RuntimeWarning: coroutine 'BHyveWebsocketEntity.async_update' was never awaited super().async_update()`

Any ideas please

**Comment by sebr** [comment]
Fixed in 3.2.2. Apologies for the delay.
