### ISSUE TITLE
Orbit B-hyve integration has been broken for some time for me

### ISSUE THREAD

**Issue by asutcliffe38** [sebr/bhyve-home-assistant#227]
**Describe the bug**
I see several errors in the logs and, the battery level is still inaccurate and the integration reports almost no information for zones etc. It's been like this for me for multiple months now. 
**Expected behaviour**
Not to produce errors in the logs , accurate battery reporting, ability to switch zones on/off 

Device:
https://www.amazon.com/dp/B09KJZKVNS?ref=nb_sb_ss_w_as-reorder_k0_1_10&amp=&crid=2OK5ZR4DC28RX&amp=&sprefix=b+hyve+hos

Firmware ver: 58

App reports current battery level as 45%....the web platform reports battery is 52%...so i don't know what to believe.

I  will post diag logs after a period of time, I have them turned on currently. In the meantime, I see these errors 

Logger: py.warnings
Source: custom_components/bhyve/sensor.py:155
Integration: Orbit B-hyve ([documentation](https://github.com/sebr/bhyve-home-assistant/blob/main/README.md))
First occurred: October 23, 2023 at 11:34:26 AM (171 occurrences)
Last logged: 1:35:24 AM

/config/custom_components/bhyve/sensor.py:155: RuntimeWarning: coroutine 'BHyveWebsocketEntity.async_update' was never awaited super().async_update()
Please attach the Home Assistant diagnostics for the B-hyve device. Sensitive information is redacted when compiling the diagnostic data.

Logger: homeassistant.components.switch
Source: helpers/entity_platform.py:359
Integration: Switch ([documentation](https://www.home-assistant.io/integrations/switch), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+switch%22))
First occurred: October 23, 2023 at 11:29:27 AM (2 occurrences)
Last logged: 1:33:51 AM

Error while setting up bhyve platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 359, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/bhyve/switch.py", line 183, in async_setup_entry
    BHyveZoneSwitch(
  File "/config/custom_components/bhyve/switch.py", line 388, in __init__
    super().__init__(hass, bhyve, device, name, icon, SwitchDeviceClass.SWITCH)
  File "/config/custom_components/bhyve/__init__.py", line 268, in __init__
    self._setup(device)
  File "/config/custom_components/bhyve/switch.py", line 420, in _setup
    ).isoformat()
      ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'isoformat'

![2023-10-24 01_35_37-Settings – Home Assistant - Vivaldi](https://github.com/sebr/bhyve-home-assistant/assets/147404248/8047a9bc-fb52-4758-a3e2-5800f4711d5f)

**Comment by sebr** [comment]
Closed in https://github.com/sebr/bhyve-home-assistant/pull/219 and released in [3.2.1](https://github.com/sebr/bhyve-home-assistant/releases/tag/3.2.1)
