### ISSUE TITLE
Zone 2 and Zone 3 starts at the same time

### ISSUE THREAD

**Issue by peterf9** [sebr/bhyve-home-assistant#233]
**Describe the bug**
when triggered zone 2 triggers zone 3 and it's not logged, while the reverse action does not trigger zone 2.

**Expected behaviour**
trigger zone 2 and just start zone 2

**BHyve devices**
Orbit 57925 B-hyve Smart 8-Zone Indoor

**Device Diagnostics**

**Comment by sebr** [comment]
Closing due to lack of useful information
