### ISSUE TITLE
All Entities States are unknown 

### ISSUE THREAD

**Issue by CrouchingWorm** [sebr/bhyve-home-assistant#24]
Hi,
Apologies I don't have logs to provide as my .bhyve directory doesn't seem to have anything in it..
I think I've enabled Debugging per your guide.

Problem:
Since version 1.00 I've not been able to connect to my bhyve account.
Each of my Entities have unknown states.
I did see a websocket error in the log, hence I enabled debudding, but can't seem to see the dump files.
I've restarted HASSIO a number times to try to generate files (by trying to connect to my account).

I'm not what more I can provide.
My BHyve environment is simply a Wifi-Hub & Smart Hose Timer.
The BHyve app seems to work okay, although it doesn't always water per the smart-scheduling, but suspect it's their app..

I've not created an automation to update, do I need to?
Apologies, by skillset is low in this space.

< Update >
I've just seen in another issue you suggest removing the previous config. I'll do that to test.

Ps. THANKS SO MUCH, this is a great integration.

Cheers,

**Comment by sebr** [comment]
@CrouchingWorm the will be in the `home-assistant.log` file not in the `.bhyve` directory :)

Can you also please upload a screenshot of your entities page filtered with `bhyve`?

<img width="1286" alt="Screen Shot 2020-06-26 at 12 06 47 pm" src="https://user-images.githubusercontent.com/81972/85813030-8493ff80-b7a5-11ea-8e6c-e826394d8e64.png">

**Comment by CrouchingWorm** [comment]
I'm removing all the entries, removing the integrations, then re-apply
(restarting really), I'll let you now.
Thanks for the speedy response!

**Comment by CrouchingWorm** [comment]
[image: image.png]

bhyve:
  username: me@me.com
  password: some_password

switch:
  - platform: bhyve
sensor:
  - platform: bhyve
  - platform: template
    sensors:
      rain_delay_gardenbed_finishing:
        friendly_name: "Rain Delay Garden Bed Finishing"
        availability_template: "{{
states('binary_sensor.rain_delay_smart_hose_timer') != 'unavailable' }}"
        value_template:
"{{(as_timestamp(state_attr('binary_sensor.rain_delay_smart_hose_timer',
'started_at')) + state_attr('binary_sensor.rain_delay_smart_hose_timer',
'delay') * 3600) | timestamp_local }}"

      rain_delay_smart_hose_timer_remaining:
        friendly_name: "Rain Delay Garden Bed Remaining"
        unit_of_measurement: "h"
        availability_template: "{{
states('binary_sensor.rain_delay_smart_hose_timer') != 'unavailable' }}"
        value_template:
"{{((as_timestamp(state_attr('binary_sensor.rain_delay_smart_hose_timer',
'started_at')) + state_attr('binary_sensor.rain_delay_smart_hose_timer',
'delay') * 3600 - as_timestamp(now())) / 3600) | round(0) }}"

  - platform: template
    sensors:
      gardenbed_next_watering:
        friendly_name: "Next watering"
        availability_template: "{{ states('switch.zone') != 'unavailable'
}}"
        value_template: >-
          {% set program = state_attr('switch.zone', 'watering_program') -%}
          {% if program and (program | count > 0) %}
            {{ as_timestamp(program[0]) | timestamp_local }}
          {% else %}
            unknown
          {% endif %}

**Comment by CrouchingWorm** [comment]
> @CrouchingWorm the will be in the `home-assistant.log` file not in the `.bhyve` directory :)

:) thank you. I'll look in there. I think I've new entities now (_2) which might be working..

**Comment by CrouchingWorm** [comment]
I think we're all good. I'll go an remove the original entities!
You're great thank you.

**Comment by CrouchingWorm** [comment]
Thank you again.
