### ISSUE TITLE
Service bhyve.set_manual_preset_runtime does not function

### ISSUE THREAD

**Issue by CursedDog19** [sebr/bhyve-home-assistant#25]
I tried to call the service in node red with the data entry { "minutes":2 } and the specified zone still ran for 10 minutes.
I also tried to call the service in home assistant to no avail.

**Comment by qwserty** [comment]
What service are you calling? You have to use bhyve.start_watering
This is my setup in my automation.yaml and works just like it should. I've haven't done anything in node red yet so I'm unsure if it would be different, but you can't use the switch.turn_on service call it has to be bhyve.start_watering or the system will just default to the 10 minute timer.

- id: 'Irrigation Front yard'
  alias: 'Irrigation Front Yard'
  description: Start the Front Yard sprinklers
  trigger:
  - at: 04:24:00
    platform: time
  - at: 05:24:00
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - thu
  action:
  - service: bhyve.start_watering
    entity_id: switch.frontyard_sprinklers_zone_2
    data:
      minutes: 19

**Comment by CursedDog19** [comment]
In a recent update there was a service added called “bhyve.set_manual_preset_runtime” which can chance the manual preset runtime for any or all stations. What I’m trying to do is create an input number in frontend that calls that service each time it is changed. Then, whenever someone turns on a station, it will run for x minutes which is determined by the input number.  
My issue is that this service does not change the preset run time. It is always at 600 seconds or 10 minutes.

**Comment by sebr** [comment]
Yep, I think there's a bug here. It doesn't work for me anymore either - maybe it never did 🙈

In the meantime @CursedDog19 as a workaround you can use the `start_watering` service as @qwserty suggests.

**Comment by CursedDog19** [comment]
Will do. Keep up the good work!

**Comment by DaftHonk** [comment]
This may be a bug in the b-hyve firmware. I have 2 hose faucet timers and have set both to 15 minutes default in the app under `My B-hyve -> Devices -> Device Detail -> Preset Runtime` but when I select Water Manually from the home screen it still defaults to 10 minutes. Setting it from HA updates the value in the app under Device Detail, but again is not obeyed when selecting Water Manually.

**Comment by sebr** [comment]
I've removed `bhyve.set_manual_preset_runtime` from the README and from exported services as I cannot get this to work. I've left the code in the repo should anybody want to take a look and debug :)
