### ISSUE TITLE
B-Hyve flood sensors displaying temperature data in F always (cannot switch to C in Home Assistant UI)

### ISSUE THREAD

**Issue by cmegalodon** [sebr/bhyve-home-assistant#257]
**Describe the bug**
The B-Hyve flood sensor temperature sensor always displays data in degrees F, and cannot be switched to display in degrees C.

**Expected behaviour**
I expected that the display units would follow the settings in Home Assistant.

**BHyve devices**
3 devices, flood sensors

**Device Diagnostics**
[config_entry-bhyve-ee4165ea31df02d5370dfb61a81dac33.json](https://github.com/user-attachments/files/16600184/config_entry-bhyve-ee4165ea31df02d5370dfb61a81dac33.json)

**Comment by sebr** [comment]
@cmegalodon I think I have fixed this, but can't confirm as I don't have a flood sensor. Can you please install [3.2.5-beta0](https://github.com/sebr/bhyve-home-assistant/releases/tag/3.2.5-beta0) and let me know how you go?

**Comment by cmegalodon** [comment]
Thank you for the very prompt work on this... however, I got an error that the integration failed to load (see debug logs attached).

**Comment by sebr** [comment]
@cmegalodon can you please attach the debug log directly to the GitHub issue (not via email response) - it's not attached

**Comment by cmegalodon** [comment]
[home-assistant_bhyve_2024-08-14T16-05-44.220Z.log](https://github.com/user-attachments/files/16619702/home-assistant_bhyve_2024-08-14T16-05-44.220Z.log)
