### ISSUE TITLE
HACS bhyve Configuration error

### ISSUE THREAD

**Issue by sjmotew** [sebr/bhyve-home-assistant#27]
Bhyve through HACS noting following configuration error:
Platform error binary_sensor.bhyve - No module named 'custom_components.bhyve.binary_sensor'

I suspect this is due to a change in binary battery sensor, not sure how to fix.

Thanks.

**Comment by sebr** [comment]
The `binary_sensor` component is no longer provided - please see the [release notes](https://github.com/sebr/bhyve-home-assistant/releases/tag/1.0.0)
