### ISSUE TITLE
Since the update 112

### ISSUE THREAD

**Issue by djiesr** [sebr/bhyve-home-assistant#29]
I got this error since the 112

_**Configuration invalide
                          Platform error binary_sensor.bhyve - No module named 'custom_components.bhyve.binary_sensor'**_

I try to uninstall and reinstall and I remove all reference to Bhyve in HA, I always got this error.

**Comment by sebr** [comment]
As per the release notes, the binary sensor was removed in [version 1.0.0](https://github.com/sebr/bhyve-home-assistant/releases/tag/1.0.0) of this integration
