### ISSUE TITLE
switch.bhyve_zone entity has two watering_program attributes

### ISSUE THREAD

**Issue by jayscovill** [sebr/bhyve-home-assistant#31]
The switch.bhyve_zone entity returns two attributes for watering_program.  Once displays an array of the next eight watering schedules.

The second returns a null value.  

When trying to create a template sensor that displays the next eight watering schedules the attribute with the null value is displayed instead.

I believe this is a bug regardless of which one is the correct attribute.  It would be great to be able to extract the next eight watering schedules out of the array though!

**Comment by jayscovill** [comment]
This is not a bug at all...I didn't read the documentation closely enough.  The watering_program attribute is a child attribute of the program_e attribute as noted in the documentation.  

{{ (states.switch.bhyve_zone.attributes.program_e.watering_program) }} returns the values for the next watering events.

{{ (states.switch.bhyve_zone.attributes.program_e.watering_program) [0,1,2,3,...] }} returns the individual values.

**Comment by sebr** [comment]
Hi @jayscovill glad you sorted this one out :). You can also take a look at the [bhyve_next_watering.py](https://github.com/sebr/bhyve-home-assistant/blob/main/python_scripts/bhyve_next_watering.py) script for more inspiration on creating new sensors which display the next watering time.

**Comment by jayscovill** [comment]
Thanks! I'm giving that a go but I use Node Red and trying to do the service call from there.  It requires a domain for the service call but I can't find anywhere what I'd set that domain to for this script.  Any hints?

**Comment by jayscovill** [comment]
LOL why do I always figure out the problem right AFTER I post in the community looking for help?

Figured it out.  domain: python_script: service: bhyve_watering_next_watering
