### ISSUE TITLE
What models does this work with please?

### ISSUE THREAD

**Issue by DPH** [sebr/bhyve-home-assistant#32]
Hi, this looks really exciting. Your write up doesn't say if it works with the B-HYVE HOSE FAUCET TIMER.
Hopefully yes and I can try it out.

Cheers David

**Comment by sebr** [comment]
@DPH,
I suppose I should be more explicit in the readme :). Yes, the integration is designed for the faucet timer. You will need the wifi hub to provide internet connectivity to the hub (bluetooth is not supported).

**Comment by DPH** [comment]
Thanks for your fast reply.
Cheers David
