### ISSUE TITLE
bhyve_next_watering.py: Difference in sensor naming between documentation and implementation

### ISSUE THREAD

**Issue by jayscovill** [sebr/bhyve-home-assistant#33]
It's me again! LOL

I just wanted to raise an issue with regards to a difference between the bhyve_next_watering.py script documentation and what I'm seeing in actual implementation.

The documentation states that the the next watering sensor will be named: `sensor.next_watering_{device_name}`

My sensor is named: `sensor.<zone name>_next_watering` where `<zone name>` is the name I gave the zone in the Bhyve app.

Checked the code and it's indeed using <zone_name> to build the sensor entity.

Also the rain delay sensor is actually created as `sensor.<device_name>_rain_delay_finishing` rather than `sensor.rain_delay_finishing_<device_name>`

Helpful script! Thanks!

**Comment by sebr** [comment]
You're right, thanks @jayscovill! I forgot to update the readme.
