### ISSUE TITLE
Python Script returning "None" for both sensors

### ISSUE THREAD

**Issue by vmcosco** [sebr/bhyve-home-assistant#34]
My B-Hyve is currently on a rain delay and I have a program set to run.  I ran the python script and it returned "none" for both the rain delay and next watering sensors.   There are no errors reported in the log.

I used `entity_id: switch.bhyve_front_central_zone`.  I did rename the switch entities from the default format, not sure if that could be the reason.

The script did create the following sensors:
`sensor.front_central_next_watering`
`sensor.home_rain_delay_finishing`

Screenshot of the attributes for `switch.bhyve_front_central_zone`

![image](https://user-images.githubusercontent.com/16504592/87675041-ddbbd700-c744-11ea-9cb9-ebeef1f13cd2.png)

Let me now if there is additional data that I can provide.

**Comment by sebr** [comment]
Hi @vmcosco 

**Next watering**: Currently there is a limitation with the `next_watering` script that it only works for smart watering programs - it's on the todo to expand this to support manual programs :)

**Rain delay finish**: Did you change the entity ids for the rain delay switch too? The script assumes the rain delay entity is: `switch.{device}_rain_delay`, i.e in your case: `switch.home_rain_delay`. It would be possible to include this as an option to the script, but for now I would suggest that you edit the `bhyve_next_watering.py` script.

**Comment by sebr** [comment]
@vmcosco ping, did you have a response to the above? Thanks :)

**Comment by vmcosco** [comment]
I had changed the name of the rain delay switch as well. Changing the name in the script worked well

**Comment by sebr** [comment]
okay thanks for the update, i'll close this ticket off as it isn't designed to support renamed entities.
