### ISSUE TITLE
Battery level unknown

### ISSUE THREAD

**Issue by BornTKill** [sebr/bhyve-home-assistant#35]
Dear,

First of all I would like to thank you for your awesome work!

Is there a known issue on battery level reporting ?
Currently it’s « unavailable » or « unknown » in HA.
I have a Smart Hose Tap with WiFi Hub

Thank you for you assistance.

**Comment by sebr** [comment]
@BornTKill no known issues. Check that you don't have any duplicate entities with `_2`

**Comment by BornTKill** [comment]
Hello,

After a while the report is Ok. Sorry for bothering you.
