### ISSUE TITLE
Websocket closed error

### ISSUE THREAD

**Issue by ecfitzgerald** [sebr/bhyve-home-assistant#37]
I get the following errors when I try to activate any switch.

Logger: custom_components.bhyve.pybhyve.websocket
Source: custom_components/bhyve/pybhyve/websocket.py:163
Integration: Orbit BHyve Integration (documentation)
First occurred: 3:54:54 PM (10 occurrences)
Last logged: 8:00:34 PM

Tried to send message whilst websocket closed

Maybe missed a setting somewhere?

**Comment by sebr** [comment]
@ecfitzgerald can you please take a look at `home-assistant.log` and paste any logs which contain `custom_components.bhyve`?

There have been some other reports of the websocket connection dropping out (see #28) which I haven't been able to reliably reproduce to fix.

Thanks

**Comment by ecfitzgerald** [comment]
You can close this and I'll follow 28, I figured out how to increase the log level and it works of course, will dig in again if it fails again.
