### ISSUE TITLE
bhyve_next_watering.py does not run

### ISSUE THREAD

**Issue by steveof2620** [sebr/bhyve-home-assistant#40]
**Describe the bug**
An error is recorded in the Home Assistant logs when attempting to run bhyve_next_watering.py.

**Expected behaviour**
creates or updates entities named sensor.{zone_name}_next_watering and sensor {device_name}_rain_delay_finishing.

**BHyve devices**
1 x B-Hyve zone /  BHyve Hose Faucet Timer / WIFI module

**Logs**
```
Logger: homeassistant.components.python_script
Source: components/python_script/__init__.py:147
Integration: Python Scripts (documentation, issues)
First occurred: 1:41:38 PM (1 occurrences)
Last logged: 1:41:38 PM

Error loading script bhyve_next_watering.py: Line 28: "_LOGGER" is an invalid variable name because it starts with "_"
```

**Comment by sebr** [comment]
Oops, thanks for the report. I've fixed by reverting to an older, functioning version of the script.

Note that the script only works for devices configured on Smart Watering programs (for now)

**Comment by steveof2620** [comment]
Thanks for your work. Your integration is very useful.
