### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by DavidPper** [sebr/bhyve-home-assistant#44]
I am new to home assistant and yaml, and the first items i wanted to automate was my irrigation system.

i have no idea what i am doing as this is the first intergration i have installed using HACS.
Orbit B-hyve is listed in HACS installed intergrations, however i dont see it listed in HA intergration list.

I have copied your config file to configuration.yaml and also added my user and password to secrets.yaml

but i dont know what to do from here, any help or example setups would be fantastic

Regards
Dave
Home Assistant NOOB

**Comment by sebr** [comment]
Hi @DavidPper 
Once you've added the `bhyve` platform into `configuration.yaml`, please restart Home Assistant. The integration will retrieve your devices and you will be able to add them into your lovelace dashboard through the UI. You can see these entities in the HA configuration page if you need a reference.

Here's an example of mine:

![screenshot-rocks](https://user-images.githubusercontent.com/81972/99003275-f2449a80-2591-11eb-9c7c-9e38ff82f55f.jpeg)

**Comment by DavidPper** [comment]
@sebr Thankyou very much, all that was needed was for me to restart Home Assistant.
This has been a massive learnig curve, i had been using openHAB for a couple of years and decided to make the switch to Home Assistant.
Again thankyou very much
Dave
