### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Seanl00045073** [sebr/bhyve-home-assistant#46]
**Describe the bug**
 zones time out very quickly and throw up a fault message but work when manually activating even though voltage is good with brand new solanoids 

**Expected behaviour**
 should be an option for a selected amount of retry attempts or an extended timer

**BHyve devices**
 6 zones

**Logs**

```log
DEBUG (MainThread) [custom_components.bhyve] Devices:
DEBUG (MainThread) [custom_components.bhyve] Programs:
```

**Comment by sebr** [comment]
What's the actual error which is provided? Please follow the instructions by providing the appropriate logs.

**Comment by Seanl00045073** [comment]
[cid:DD6B91FD-C107-48E6-9D65-A82095F8C7F9-L0-001]

- Sean

On 22 Nov 2020, at 1:06 pm, Seb Ruiz <notifications@github.com> wrote:

﻿

What's the actual error which is provided? Please follow the instructions by providing the appropriate logs.

**Comment by sebr** [comment]
This error is meaningless to me - where does it come from?

**Comment by sebr** [comment]
Closing as there hasn't been any further information - please provide logs as instructed in the issue template.
