### ISSUE TITLE
Unable to see Bhyve under configuration/intigration of HASSIO

### ISSUE THREAD

**Issue by shsurury** [sebr/bhyve-home-assistant#48]
I have installed HACS and am able to install Orbit Bhyve through HACS but no matter what I do I am not able to find it under configuratio/ intigration of Home Assistant. I have tried deleting the cache several time but I still cant install it. Please help.

![Screenshot 2020-11-27 213411](https://user-images.githubusercontent.com/7891577/100440028-5fab0c00-30f8-11eb-9ecc-877b238a0ece.png)
![Screenshot 2020-11-27 213148](https://user-images.githubusercontent.com/7891577/100439809-1fe42480-30f8-11eb-9bee-04fd2ae703be.png)
![Screenshot 2020-11-27 213219](https://user-images.githubusercontent.com/7891577/100439819-22df1500-30f8-11eb-860c-c4bb55d5f2d5.png)

**Comment by sebr** [comment]
This integration isn't available to configure via the UI. It needs to be configured with YAML in `configuration.yaml`

Instructions on how to do this are in the [README](https://github.com/sebr/bhyve-home-assistant#configuration)

**Comment by shsurury** [comment]
Thanks Seb,
Much appreciated

Regards

Sajid Husain Surury
Food Safety Auditor & Consultant
B. Sc., M. Sc., M. App. Sc., MAIFST
RABQSA # 113236
Mobile – 0400571140<tel:0400571140>
Phone/Fax – 03 8839 0538<tel:03%208839%200538>
E mail – sajid@surury.com.au<mailto:sajid@surury.com.au>

On 29 Nov 2020, at 22:47, Seb Ruiz <notifications@github.com> wrote:

﻿

This integration isn't available to configure via the UI. It needs to be configured with YAML in configuration.yaml

Instructions on how to do this are in the README<https://github.com/sebr/bhyve-home-assistant#configuration>
