### ISSUE TITLE
Unable to retrieve watering program if the smart watering is disabled

### ISSUE THREAD

**Issue by jaganath-b** [sebr/bhyve-home-assistant#5]
Hi,
Thanks for your great work with this integration. I just completed the setup and everything seems to be working fine except the watering program. It works ONLY if the smart watering is "ON". I have enabled the regular program mode in the Bhyve which waters based on the manually set schedule. Is there is any option to retrieve the watering program even if the Smart Watering is "OFF".

Thanks again for your help.

**Comment by sebr** [comment]
Hi @jaganath-b 
Sure, have the data so it would be fairly straightforward. I would love your thoughts on how to make it available, however.

For smart watering programs, the API reports a list of watering dates & times, similar to this:
```
{
    "name": "Smart Watering",
    "watering_plan": [
      {
        "run_times": [],
        "start_times": [],
        "date": "2019-12-16T13:00:00.000Z"
      },
      {
        "run_times": [],
        "start_times": [],
        "date": "2019-12-17T13:00:00.000Z"
      },
      {
        "run_times": [{ "run_time": 15, "station": 1 }],
        "start_times": ["07:30", "07:55"],
        "date": "2019-12-18T13:00:00.000Z"
      }]
}
```

However for manual programs, the API doesn't report the calculated day/times, but rather the base configuration:

```
{
    "name": "Backyard",
    "frequency": { "type": "days", "days": [1, 4] },
    "updated_at": "2019-03-20T02:00:00.331Z",
    "start_times": ["07:30"],
    "device_id": "<device_id>",
    "program": "a",
    "run_times": [{ "run_time": 20, "station": 1 }]
  }
```

I could add the frequency & run time fields to the zone (station) attributes. Would that be helpful?

**Comment by jaganath-b** [comment]
Hi @sebr ,

Yeah, that should help. All i need is to come up with the next watering schedule (date & time) using these parameters. I presume these fields can be used in templates to come up with the schedule. Can you also include start times field?

**Comment by sebr** [comment]
@jaganath-b is there a reason you closed this? I have yet to implement this change. If you no longer need it or have another solution it would be helpful to know this.

**Comment by jaganath-b** [comment]
Sorry mate...I closed it by mistake..reopened it now..I'm still looking forward for your change.. thanks

**Comment by sebr** [comment]
@jaganath-b give version `0.1.9` a shot

**Comment by jaganath-b** [comment]
Hi @sebr . 
I could see 0.1.8, but not 0.1.9 yet

**Comment by jaganath-b** [comment]
@sebr ,
Updated to 0.1.9, but still couldn't see the frequency & start time if its set to manual. Below is the zone parameters when its set to manual. Smart watering enabled parameter shows as **true** even though i disabled it in the Bhyve app. Let me know if you need any more info. Thanks again for your help.

manual_preset_runtime: 600 
smart_watering_enabled: true 
sprinkler_type: rotor 
image_url: <>
watering_program:  
started_watering_station_at: null 
friendly_name: Backyard Zone 
icon: mdi:water-pump 
entity_picture: <>
device_class: switch

**Comment by sebr** [comment]
@Jaganath-b

Can you please enable debug logging as per the readme and restart HA? Once you’ve done this the device list and watering program will be printed to the log. Can pase share this?

Thanks!

**Comment by jaganath-b** [comment]
@sebr ..here you go
Devices: [{'last_connected_at': '2020-02-20T13:32:44.873Z', 'address': 'REDACTED', 'water_sense_mode': 'auto', 'scheduled_modes': {'auto': {'at': '', 'annually': False}, 'off': {'at': '', 'annually': False}}, 'timezone': {'dst_offset': 0, 'raw_offset': 36000, 'timezone_id': 'Australia/Sydney', 'timezone_name': 'Australian Eastern Standard Time'}, 'full_location': 'REDACTED', 'weather_forecast_location_id': 'XXXXX', 'firmware_version': '0039', 'name': 'Smart Outdoor Timer', 'type': 'sprinkler_timer', 'manual_preset_runtime_sec': 600, 'battery': None, 'restricted_frequency': {'type': 'days', 'days': [0, 2, 5], 'restricted_times': []}, 'weather_delay_thresholds': {'precip_prob': 30, 'precip_in': 0.125, 'wind_speed_mph': 20, 'freeze_temp_f': 37}, 'updated_at': '2020-02-22T22:26:32.926Z', 'reference': 'XXXXX', 'mac_address': 'XXXXX', 'weather_station_id': 'XXXXXX', 'mesh_id': 'XXXXX', 'status': {'run_mode': 'auto', 'next_start_programs': ['a'], 'rain_delay_overridden_at': '2019-03-13T07:05:51.925Z', 'watering_status': None, 'rain_delay_suggested_at': '2020-02-12T19:04:17.111Z', 'rain_delay': 0, 'flow_sensor': None, 'next_start_time': '2020-02-26T02:30:00+11:00', 'rain_delay_started_at': '2019-08-29T06:41:28.000Z'}, 'wifi_version': 0, 'id': 'XXXXX', 'num_stations': 6, 'notes': '', 'zones': [{'station': 1, 'slope_grade': 4, 'sun_shade': 'partial_shade', 'name': 'Backyard', 'image_url': 'XXXXX', 'num_sprinklers': 6, 'soil_type': 'sandy_loam', 'catch_cup_volumes': [], 'catch_cup_run_time': 0, 'smart_watering_enabled': False, 'sprinkler_type': 'rotor'}, {'station': 2, 'slope_grade': 4, 'sun_shade': 'partial_shade', 'name': 'Frontyard', 'XXXXX', 'num_sprinklers': 1, 'soil_type': 'sandy_loam', 'catch_cup_volumes': [], 'catch_cup_run_time': 0, 'smart_watering_enabled': False, 'sprinkler_type': 'rotor'}], 'user_id': 'XXXXX', 'google_home_status': {'will_report_state': True, 'user_id': 'XXXX', 'request_id': None}, 'device_gateway_topic': 'devices-1', 'hardware_version': 'WT25G2-0001', 'is_connected': True, 'location': 'REDACTED', 'created_at': '2019-01-12T04:08:20.634Z', 'suggested_start_time': '02:30', 'et_id': 'XXXX'}]

Programs: [{'name': 'Lawn Watering', 'program_start_date': None, 'frequency': {'type': 'interval', 'interval': 3, 'interval_start_time': '2020-02-17T08:00:00.000Z'}, 'program_end_date': None, 'updated_at': '2020-02-22T22:26:32.923Z', 'updated_via': None, 'start_times': ['02:30'], 'id': 'XXXX', 'budget': 100, 'is_smart_program': False, 'device_id': 'XXXX', 'program': 'a', 'run_times': [{'run_time': 45.0, 'station': 1}, {'run_time': 30.0, 'station': 2}], 'enabled': True, 'created_at': '2020-02-18T01:45:45.888Z'}]
