### ISSUE TITLE
Include Orbit 57995 B-hyve XR

### ISSUE THREAD

**Issue by crboffo** [sebr/bhyve-home-assistant#58]
Any chance to include the compatibility of the latest Orbit 57995 B-Hyve XR? It seems partially compatible?

**Comment by sebr** [comment]
Hi @crboffo,
Can you please elaborate what you mean by "partially compatible"?

What features work or do not work? This device isn't available in Australia, if you want to gift one and send it to me I'd be more than happy to oblige ;-)

**Comment by crboffo** [comment]
Thank you for the reply. I get the status sensors and the delay switch but
none of the other sensors generated by the integration.

**Comment by sebr** [comment]
Okay thanks, it would be helpful if you could please enable debugging and send me the response from the BHyve API. Follow these instructions:

Step 1: Enable debugging.

Add the following to `configuration.yaml` and then restart Home Assistant.
```
logger:
  logs:
    custom_components.bhyve: debug
```

Step 2: Check Home Assistant logs

1. Open `home-assistant.log`
2. Upload the lines which begin with:
```log
DEBUG (MainThread) [custom_components.bhyve] Devices:
DEBUG (MainThread) [custom_components.bhyve] Programs:
```

**Comment by crboffo** [comment]
Thanks for looking into this.
Attached is an extract of the log file.

**Comment by sebr** [comment]
@crboffo there was no attachment uploaded, most likely because you replied using email. Can you please attach directly to the github issue? thx

**Comment by crboffo** [comment]
Here it is.

[b-hyve.log](https://github.com/sebr/bhyve-home-assistant/files/6381421/b-hyve.log)

**Comment by sebr** [comment]
@crboffo as far as I can tell, the integration should be working... Can you please navigate to your HA's admin page under `/config/entities`, search by `bhyve` and then provide screenshots to show me what entities have been created?

As well as this, all other logs (with debugging enabled) which relate to `customer_components.bhyve`.

Thank you

**Comment by crboffo** [comment]
Never mind, it took a couple of days, but this morning all the sensors showed up as you have in your repository.
Anyways thank you for looking into it so quickly and I guess now you can add this model to your list
