### ISSUE TITLE
Don't create battery sensors for devices without batteries

### ISSUE THREAD

**Issue by akballow** [sebr/bhyve-home-assistant#61]
What does this entity track exactly? the backup battery? Something else? I can not figure out what it tracks to troubleshoot it because it always says unknown.  My Device does have a battery for remembering the settings which did display empty when i did not pull the tab out from a new install, but maybe that is not what it is for. I have the 6-zone outdoor unit.

Sorry for not using the template but, there is no general question

**Comment by sebr** [comment]
Hi @akballow,
I've never used the 6-zone outdoor unit. Is it hard wired to power? I have the faucet timers which are battery operated. 

Regarding the template, no worries. In the future you can use open a [discussion conversation](https://github.com/sebr/bhyve-home-assistant/discussions)

**Comment by Madelinot** [comment]
It is hard wired.  I have both.  The battery has always shown unknown for the 6-station unit.

**Comment by sebr** [comment]
Thanks for the info - I've changed the logic to not create battery sensors if the device does not report a battery state.

**Comment by sthorley** [comment]
Hi Seb, any chance of pushing a new release with this fix included?

FYI this integration works with the 4 station system too (no battery on this model). https://www.bunnings.com.au/orbit-4-station-b-hyve-indoor-irrigation-controller_p0135882

**Comment by sebr** [comment]
Oh yes, will do!
