### ISSUE TITLE
Orbit B-hyve No Longer Works

### ISSUE THREAD

**Issue by Mudguppie** [sebr/bhyve-home-assistant#72]
Several months back, I had the B-Hyve single faucet controller working fine on my Home Assistant installation.  Since that time, HA has listed it as unavailable. I’ve tried checking the Orbit B-hyve app using my logon info and it works.  However, using that same logon in my configuration.yaml file, it doesn’t seem to work.  It lists those entities as unavailable in the Lovelace screen.  When I check the status of the entities in the configuration tab of HA, it has a symbol of a red exclamation point with a circle around it.  I don’t know what that means.  

I tried to enable the logger by copying and pasting the commands from the B-hyve GitHub instructions but my configuration.yaml doesn’t like it. I’m at a loss as to what to try next.

**Comment by sebr** [comment]
Hi @Mudguppie 
I'll need those debug logs - without it I won't be able to help. YAML is a very precise syntax so check that your formatting is correct.

**Comment by Mudguppie** [comment]
Okay, Seb. I was able to enable the debug log for b-hyve per the instructions.  Where might I find that log to send it to you?
Thanks. 


Sent from AT&T Yahoo Mail for iPad


On Tuesday, July 20, 2021, 6:52 AM, Seb Ruiz ***@***.***> wrote:




Hi @Mudguppie
I'll need those debug logs - without it I won't be able to help. YAML is a very precise syntax so check that your formatting is correct.

**Comment by Mudguppie** [comment]
Hi Seb,
This is one of the B-hyve errors I found it the log.  It appeared twice in the log 

This error originated from a custom integration.
Logger: custom_components.bhyveSource: custom_components/bhyve/__init__.py:271 Integration: Orbit BHyve Integration (documentation) First occurred: 11:07:03 PM (1 occurrences) Last logged: 11:07:03 PM
Failed to connect to BHyve servers. Error requesting data from https://api.orbitbhyve.com/v1/watering_events/603417ae4f0c935e1b5fc250: Seb  500, message='Internal Server Error', url=URL('https://api.orbitbhyve.com/v1/watering_events/603417ae4f0c935e1b5fc250?t=1626840422.9410443&page=1&per-page=10')
I also saw this entry…
This error originated from a custom integration.
Logger: homeassistant.helpers.entitySource: custom_components/bhyve/pybhyve/client.py:78 Integration: Orbit BHyve Integration (documentation) First occurred: 11:07:03 PM (2 occurrences) Last logged: 11:07:03 PM
Update for sensor.patio_plant_irrigation_battery_level failsUpdate for sensor.zone_history failsTraceback (most recent call last):  File "/config/custom_components/bhyve/pybhyve/client.py", line 75, in _request    resp.raise_for_status()  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status    raise ClientResponseError(aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.orbitbhyve.com/v1/devices?t=1626840422.9390047')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 401, in async_update_ha_state    await self.async_device_update()  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 609, in async_device_update    raise exc  File "/config/custom_components/bhyve/sensor.py", line 107, in async_update    await self._refetch_device()  File "/config/custom_components/bhyve/__init__.py", line 264, in _refetch_device    raise (err)  File "/config/custom_components/bhyve/__init__.py", line 253, in _refetch_device    device = await self._bhyve.get_device(self._device_id, force_update)  File "/config/custom_components/bhyve/pybhyve/client.py", line 174, in get_device    await self._refresh_devices(force_update=force_update)  File "/config/custom_components/bhyve/pybhyve/client.py", line 87, in _refresh_devices    self._devices = await self._request(  File "/config/custom_components/bhyve/pybhyve/client.py", line 78, in _request    raise RequestError(f"Error requesting data from {url}: {err}")custom_components.bhyve.pybhyve.errors.RequestError: Error requesting data from https://api.orbitbhyve.com/v1/devices: 500, message='Internal Server Error', url=URL('https://api.orbitbhyve.com/v1/devices?t=1626840422.9390047')
I’m sure this makes more sense to you than it does me.
Best regards,
Robert


Sent from AT&T Yahoo Mail for iPad


On Tuesday, July 20, 2021, 6:52 AM, Seb Ruiz ***@***.***> wrote:




Hi @Mudguppie
I'll need those debug logs - without it I won't be able to help. YAML is a very precise syntax so check that your formatting is correct.

**Comment by sebr** [comment]
Hi @Mudguppie this is a common error reported by the Orbit API and shouldn't impact your experience using the integration if you are using [version 2.0.8](https://github.com/sebr/bhyve-home-assistant/releases/tag/2.0.8).

If you are still experiencing the issue, can you please raise a [new issue using the template](https://github.com/sebr/bhyve-home-assistant/issues/new?assignees=&labels=&template=bug_report.md&title=) which provides instructions on how to access the relevant debugging logs.

Thanks
