### ISSUE TITLE
feature request, set zone moisture levels

### ISSUE THREAD

**Issue by gdlesage** [sebr/bhyve-home-assistant#73]
**Is your feature request related to a problem? Please describe.**

In the bhyve app, there is the ability to adjust soil moisture level value,  (home-> zones -> zone one -> soil moisture).  Setting soil moisture determines how much and how often smart water occurs, its a dynamic value based on location and weather.  I have soil moisture sensors and  I would like to use those sensors to adjust this bhyve soil moisture levels periodically.

**Describe the solution you'd like**

Add to the integration a entity that resets bhyve soil moisture level value.  Users with soil moisture sensors or by other determinates, can change bhyve soil moisture level valve which I anticipate would increase accuracy of the bhyve smart water program
**Describe alternatives you've considered**

**Additional context**

**Comment by sebr** [comment]
Released in version 2.2.0
