### ISSUE TITLE
Invalid Config

### ISSUE THREAD

**Issue by grouts112** [sebr/bhyve-home-assistant#75]
Issue:-
Since HA 2021.7.0 (maybe 2021.6.x) and still getting it at 2021.7.4
I am receiving regular error notifications for the b·hyve plugin..

Bhyve devices:-
HT25-0000
BH1-0001

LOGS:-

In HA notification..

Invalid Config

The following integrations and platforms could not be set up:

bhyve
bhyve.switch
bhyve.sensor
Please check your config and logs.

The log shows…

Logger: homeassistant.setup
Source: setup.py:311 
First occurred: 4:35:15 AM (2 occurrences) 
Last logged: 4:35:15 AM

Unable to prepare setup for platform bhyve.switch: Unable to set up component.
Unable to prepare setup for platform bhyve.sensor: Unable to set up component.

**Comment by sebr** [comment]
Can you please provide your config as there is likely an error with your yaml file.

**Comment by grouts112** [comment]
Hi,   Thanks for your very quick reply !

It would surprise me if it the config, as it works 'most' of the time..
In fact, it has come good since I opened this issue>

![image](https://user-images.githubusercontent.com/56949816/127094601-557cd12b-ccec-449f-84b0-e2ed0f7e809c.png)

The yaml for the b-hyve:-
```
# orbit b-hyve tap controller
bhyve:
  username: !secret bhyve_username
  password: !secret bhyve_password
```
in switch.yaml :-
`- platform: bhyve`

and in Sensor.syaml :-
`  - platform: bhyve`

As I say, it's working currently..

![image](https://user-images.githubusercontent.com/56949816/127095111-b165764d-cea8-471e-8217-cc53dacec4f3.png)

but I do get the error per topic, regularly.

**Comment by sebr** [comment]
Are you using `2.0.8`? There are some fixes in the latest release which more gracefully handle errors in the BHyve API.

If you are, can you please provide any logs?

**Comment by grouts112** [comment]
Hi,  not sure how to tell the version that is running ?
my manifest.json file says "version": "2.0.6",  which is the same on this repository.
there are no updates available according to HACS,  so I assume the latest.

I have enabled debug logging and will provide the logs after it next does it.

**Comment by sebr** [comment]
@grouts112 how are you going with this? Are you still experiencing errors?

**Comment by grouts112** [comment]
Hi Seb,
 Sorry for not getting back sooner.
Since I enabled the additional logging I have not seen it re-occur!

I think it is safe to say you can close this issue.
Thanks for your time.

**Comment by ivkobylinskyi** [comment]
Can I have just on/off toggle. No need schedule or delay. Just on/off.

**Comment by sebr** [comment]
> Can I have just on/off toggle. No need schedule or delay. Just on/off.

You can turn a switch on/off today. Please start a new discussion if you have any queries.
