### ISSUE TITLE
B-Hyve Smart Flood Sensors

### ISSUE THREAD

**Issue by disforw** [sebr/bhyve-home-assistant#76]
B-hyve now introduced smart water sensors. They are a cheap solution that integrates nicely in to the Orbit family. Have you had any success in adding them to your integration?

**Comment by sebr** [comment]
Hi!
I was not aware that these devices existed, and to be honest don't have any need for them! So it is unlikely that I will add support.

**Comment by disforw** [comment]
Would you mind if I give it a shot and create a PR?

**Comment by sebr** [comment]
Of course not - sounds great!

**Comment by disforw** [comment]
PR created #80

**Comment by sebr** [comment]
Released in 2.1.0-beta0
