### ISSUE TITLE
Orbit B-hyve is no longer available in Home Assistant

### ISSUE THREAD

**Issue by Mudguppie** [sebr/bhyve-home-assistant#78]
**Describe the bug**

B-hyve faucet time listed as unavailable in Home Assistant. 

**Expected behaviour**

To be available and controllable from Home Assistant. 

**BHyve devices**

Orbit B-hyve single faucet timer with WiFi hub

**Logs**

DEVICES:[{"last_connected_at": "2021-08-12T01:33:32.864Z", "address": "REDACTED", "timezone": {"dst_offset": 3600, "raw_offset": -21600, "timezone_id": "America/Chicago", "timezone_name": "Central Daylight Time"}, "full_location": "REDACTED", "firmware_version": "0030", "name": "Patio Plants", "type": "bridge", "updated_at": "2021-08-12T01:33:32.864Z", "reference": "4467552183e6", "mac_address": "4467552183e6", "mesh_id": "5e83a97d4f0cb5aa0482a2d7", "status": {"watering_status": null, "next_start_time": "1970-01-01T00:00:00-05:00", "next_start_programs": []}, "wifi_version": 0, "id": "5e83a97d4f0cb5aa0482a2d5", "num_stations": 0, "user_id": "5e83a8d04f0c7eccad2f542a", "device_gateway_topic": "devices-5", "hardware_version": "BH1-0001", "is_connected": true, "location": "REDACTED", "created_at": "2020-03-31T20:35:09.556Z"}, {"last_connected_at": "2021-08-12T01:33:32.866Z", "address": "REDACTED", "water_sense_mode": "auto", "scheduled_modes": {}, "timezone": {"dst_offset": 0, "raw_offset": -21600, "timezone_id": "America/Chicago", "timezone_name": "Central Standard Time"}, "full_location": "REDACTED", "weather_forecast_location_id": "5a325b4c4f0c922b1982152c", "firmware_version": "0041", "name": "Patio Plant Irrigation", "type": "sprinkler_timer", "manual_preset_runtime_sec": 600, "battery": {"percent": 46, "charging": false}, "image_url": "https://s3-us-west-2.amazonaws.com/orbit-irrigation/device-assets/5e83a8d04f0c7eccad2f542a/b15ea7de-25ac-4883-8402-c631f118763d", "restricted_frequency": null, "weather_delay_thresholds": {"precip_prob": 30, "precip_in": 0.125, "wind_speed_mph": 20, "freeze_temp_f": 37}, "updated_at": "2021-08-12T14:10:21.204Z", "reference": "4467552183e6-18626", "mac_address": "446755140f19", "weather_station_id": "5a30261a4f0c1bde5df55547", "mesh_id": "5e83a97d4f0cb5aa0482a2d7", "status": {"run_mode": "auto", "next_start_programs": ["a"], "rain_sensors": [], "rain_delay_overridden_at": "2021-07-19T20:51:15.919Z", "watering_status": null, "rain_delay": 0, "flow_sensor": null, "next_start_time": "2021-08-15T09:00:00-05:00", "rain_delay_started_at": "2021-08-12T14:10:05.000Z"}, "id": "603417ae4f0c935e1b5fc250", "num_stations": 1, "zones": [{"station": 1, "name": "", "num_sprinklers": 0, "catch_cup_volumes": [], "catch_cup_run_time": 0, "smart_watering_enabled": false, "flow_data": {"cycle_run_time_sec": 0, "flow_rate_gpm": 0, "cycle_volume_gal": 0}}], "user_id": "5e83a8d04f0c7eccad2f542a", "google_home_status": null, "device_gateway_topic": "devices-5", "hardware_version": "HT25-0000", "is_connected": true, "location": "REDACTED", "created_at": "2021-02-22T20:44:30.488Z", "suggested_start_time": null, "et_id": "5644ff08ad27a7777ff6d887"}]
2021-08-12 09:29:50 DEBUG (MainThread) [custom_components.bhyve] Programs: [{"pending_timer_ack": "0", "update_via": "wifi", "name": "Weekly Watering", "frequency": {"type": "interval", "interval": 3, "interval_start_time": "2021-02-22T00:00:00.000Z"}, "is_basic_program": false, "updated_via": "wifi", "start_times": ["09:00"], "id": "60341add4f0c8f4b44d58acd", "budget": 100, "device_id": "603417ae4f0c935e1b5fc250", "program": "a", "run_times": [{"run_time": 10, "station": 1}], "enabled": true, "created_at": "2021-02-22T20:58:05.992Z"}]

PROGRAMS:DEBUG (MainThread) [custom_components.bhyve] Programs: [{"pending_timer_ack": "0", "update_via": "wifi", "name": "Weekly Watering", "frequency": {"type": "interval", "interval": 3, "interval_start_time": "2021-02-22T00:00:00.000Z"}, "is_basic_program": false, "updated_via": "wifi", "start_times": ["09:00"], "id": "60341add4f0c8f4b44d58acd", "budget": 100, "device_id": "603417ae4f0c935e1b5fc250", "program": "a", "run_times": [{"run_time": 10, "station": 1}], "enabled": true, "created_at": "2021-02-22T20:58:05.992Z"}]

```log
DEBUG (MainThread) [custom_components.bhyve] Devices:
DEBUG (MainThread) [custom_components.bhyve] Programs:
```

**Comment by sebr** [comment]
Are there any other notable logs?

**Comment by Mudguppie** [comment]
None other than what I included. Do you have another log that I should look at?


Sent from AT&T Yahoo Mail for iPad


On Thursday, August 12, 2021, 4:22 PM, Seb Ruiz ***@***.***> wrote:




Are there any other notable logs?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sebr** [comment]
No other log files, it would be in `home-assistant.log` perhaps as an error or warning. Search for `bhyve` :)

Without this I can't track down any possible causes - and would suggest you restart Home Assistant. The only thing I can think of is if you renamed BHyve devices or zones which could have caused the entity names to be changed.

**Comment by Mudguppie** [comment]
Now I remember, we had a hard freeze in Texas back in February and my B-hyve faucet timer froze up and busted something so I had to replace the faucet part itself. The WiFi hub is the same. I think that was about the same time I started noticing that HA would no longer recognize the B-hyve.  I used the same name for the replacement timer and it is fully recognized via the Orbit B-hyve app. How can I start from scratch again?
I have tried to uninstall the B-hyve support in HA and reinstall it several times with no success.  I have my B-hyve logon info in configuration.yaml. Is that still supported or do I just reinstall it using HACS?
Thanks for your help.


Sent from AT&T Yahoo Mail for iPad


On Thursday, August 12, 2021, 6:08 PM, Seb Ruiz ***@***.***> wrote:




No other log files, it would be in home-assistant.log perhaps as an error or warning. Search for bhyve :)

Without this I can't track down any possible causes - and would suggest you restart Home Assistant. The only thing I can think of is if you renamed BHyve devices or zones which could have caused the entity names to be changed.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sebr** [comment]
You should be able to see the entities from the BHyve app in the HA entity register (go to configuration). It's likely that the new entities have been named `my_zone_2` and you should be able to rename it from the UI.

Otherwise, disable the BHyve integration, restart HA, remove all the entities from the UI, then re-enable the integration.

**Comment by Heroj04** [comment]
I seem to be having a similar issue.  
I lost access to everything except watering program switches.  
I did just update hass to 2021.8.6 from 2021.8.1, maybe had something to do with it.

**Comment by Mudguppie** [comment]
Sorry for the delay in getting back with you but, I got sidetracked. I just wanted to let you know that once I deleted the devices from the B-hyve app and reinstalled them, the HA integration works fine.
Thanks for your help. 


Sent from AT&T Yahoo Mail for iPad


On Thursday, August 12, 2021, 6:31 PM, Seb Ruiz ***@***.***> wrote:




You should be able to see the entities from the BHyve app in the HA entity register (go to configuration). It's likely that the new entities have been named my_zone_2 and you should be able to rename it from the UI.

Otherwise, disable the BHyve integration, restart HA, remove all the entities from the UI, then re-enable the integration.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
