### ISSUE TITLE
Manual Switch 

### ISSUE THREAD

**Issue by Narraman** [sebr/bhyve-home-assistant#8]
The manual turn the switch on call includes the manual_preset_runtime in seconds but bhyve is expecting minutes, so if Bhyve is setup with a manual run of 30 minutes it returns a manual_preset_runtime of 1800s to home assistant but the manual switch call then returns 1800 to bhyve which it interprets as 30hrs and then it appears it will only accept 12hours so uses this. When I divided the preset_manual_runtime by 60 the switch run time returned to the correct  30minutes.
/
config/custom_components/bhyve/switch.pyCurrent code
current code
station_payload = [
            {"station": self._zone_id, "run_time": self._manual_preset_runtime}

revised code
  station_payload = [
            {"station": self._zone_id, "run_time": self._manual_preset_runtime/60}

**Comment by sebr** [comment]
Brilliant, thanks for catching this
