### ISSUE TITLE
Does not show up in Home assistant even though it claims to be loaded via hacs

### ISSUE THREAD

**Issue by trentjw** [sebr/bhyve-home-assistant#88]
**Describe the bug**

does not show up in integrations 
**Expected behaviour**
 should show up

**BHyve devices**
 12 zone controller

**Logs**

```log
DEBUG (MainThread) [custom_components.bhyve] Devices:
DEBUG (MainThread) [custom_components.bhyve] Programs:
```

**Comment by sebr** [comment]
Please reopen this after following instructions in the issue template.

**Comment by trentjw** [comment]
nice

**Comment by sebr** [comment]
?
