### ISSUE TITLE
Entity implements `device_state_attributes`

### ISSUE THREAD

**Issue by mdegat01** [sebr/bhyve-home-assistant#94]
**Describe the bug**

On startup of Home Assistant after updating to version `2021.12.1` with this integration in use, I received the following message in my log:

```
Entity switch.hose_default_program (<class 'custom_components.bhyve.switch.BHyveProgramSwitch'>) implements device_state_attributes. Please report it to the custom component author.
```

So as requested I am reporting it. To my knowledge this warning just started appearing in version `2021.12.1`. I am not super diligent about checking my HA logs but I check them often enough that I feel like I would've noticed it if this was happening in version `2021.11`.

**Expected behaviour**

Warning should not be logged on startup.

**Logs**
```
2021-12-13 11:50:36 WARNING (MainThread) [homeassistant.helpers.entity] Entity switch.hose_default_program (<class 'custom_components.bhyve.switch.BHyveProgramSwitch'>) implements device_state_attributes. Please report it to the custom component author.
```

**Comment by sebr** [comment]
Fixed in 2.1.1 - thanks for reporting!
