### ISSUE TITLE
I wish someone could provide a step by step guide to installing and integrating the Orbit Bhyve with Home Assistant

### ISSUE THREAD

**Issue by RobSobey** [sebr/bhyve-home-assistant#97]

**Comment by sebr** [comment]
You will need to follow the following steps:

1. Familiarise yourself with [manual configuration for Home Assistant](https://www.home-assistant.io/docs/configuration/).
2. Install [HACS](https://hacs.xyz/) (Home Assistant Community Store)
3. Install this integration via the HACS user interface
4. Configure this integration as described in the [README](https://github.com/sebr/bhyve-home-assistant#installation)

To understand the entities created, please also consult the [readme](https://github.com/sebr/bhyve-home-assistant#installation).

**Comment by RobSobey** [comment]
Hi @sebr, I have HACS installed and have installed a few other integrations from HACS. The others I have used worked without having to do anything in onfiuration.yaml. Not sure what I'm doing wrong, but I'll go through all the readme files.

**Comment by RobSobey** [comment]
I'm not sure where to put the login details? 
![image](https://user-images.githubusercontent.com/84689362/146880429-3687aca2-0aad-4569-9106-b07769c6f02e.png)

**Comment by sebr** [comment]
@RobSobey the screenshot you shared are the files from the integration itself. You need to modify Home Assistant's `configuration.yaml` which should exist at the top level of your installation directory. I'm not familiar with the "File editor" which you are using.
